# day05_03_package
- 외부 패키지 이용하기
- 날짜 다루기

In [1]:
# !pip install ~

In [61]:
import datetime as dt
import numpy as np
import pandas as pd

In [6]:
# 현재 날짜 구하기
now_dt = dt.datetime.now()

In [11]:
# now_dt를 이용하여 다음을 출력하라
now_dt
# 년도
print(now_dt.year)
# 월
print(now_dt.month)
# 일
print(now_dt.day)
# 시간
print(now_dt.hour)

2020
5
9
18


In [15]:
# 날짜를 포맷에 맞춰서 출력
now_dt.strftime('%Y-%m-%d')
now_dt.strftime('%Y / %m / %d')

'2020 / 05 / 09'

In [17]:
# 시간을 포맷에 맞춰서 출력
now_dt.strftime('%H:%M:%S')

'18:06:28'

In [20]:
# 날짜의 연산
now_dt + dt.timedelta(days=7)

datetime.datetime(2020, 5, 16, 18, 6, 28, 457661)

In [22]:
# 실습하기
# now_dt를 이용해서 1주일 이전을 출력
now_dt + dt.timedelta(days=-7)
now_dt + dt.timedelta(weeks=-1)

datetime.datetime(2020, 5, 2, 18, 6, 28, 457661)

# numpy
- 많은 숫자형 데이터를 하나의 변수에 넣고 관리할 때 사용하는 리스트는
- 속도가 느리고 메모리를 많이 차지하는 단점이 있다.
- 리스트는 추가, 삭제, 수정 등이 배열에 비해 자유롭기 때문에 속도가 느리고 사용상 이점이 있다.
- 파이썬은 리스트만 존재하고, 배열이라는 개념이 존재하지 않는다.
- 유일하게 문자열만 기본적으로 배열의 형태를 갖는다.
- 배열이 속도가 빠른 이유는 배열에 저장되는 자료형이 모두 같기 때문이다.

In [29]:
# 1차원 배열
a = np.array([1,2]) # 리스트를 배열로 변환해준다.
print(a)

[1 2]
[1, 2]


In [31]:
# 2차원 배열
# np.array() 안에는 하나의 자료구조만 들어가야 한다.
# np.array([1,2],[3,4]) -> 오류
b = np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


In [32]:
# 모양 확인하기]
# shape() : 행과 열로 리턴 (행,열)
print(a.shape)
print(b.shape)

(2,)
(2, 2)


In [34]:
# 갯수가 다를 때는 배열이 아닌 리스트 형태로 배열이 감싸준다.
c = np.array([[1,2,3],[3,4]])
c

array([list([1, 2, 3]), list([3, 4])], dtype=object)

In [37]:
# np.arange()
# range와 다르다!
# 범위에 해당하는 순차적으로 증가하는 배열을 리턴한다.
my_data = np.arange(10)

In [39]:
# my_data 배열의 모든 값에 +1씩 연산하기
my_data + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
# my_data 배열의 모든 값에 x2씩 연산하기
my_data * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [43]:
# 배열에 2가 포함되어있는지 확인 (R의 벡터와 유사)
# 벡터연산을 활용할 수 있다.
# 리스트의 경우 if조건문을 사용하여야 하지만 배열은 그럴 필요가 없다.
my_data == 2

array([False, False,  True, False, False, False, False, False, False,
       False])

In [45]:
# 실습하기
# my_data의 데이터에서 5보다 큰 데이터를 검사
my_data[my_data>5]

array([6, 7, 8, 9])

# 배열의 인덱싱(조회)

In [49]:
my_data[0]
my_data[1]
my_data[1:5]
my_data[ [1,3,5] ]
my_data[4:]
# out of index의 경우, 파이썬에서 자동으로 길이를 맞춰줌으로써 예외처리를 해준다.
my_data[4:1000]

array([4, 5, 6, 7, 8, 9])

In [51]:
# my_data의 짝수번째 방만 조회하기
my_data[my_data%2==0]

array([0, 2, 4, 6, 8])

In [54]:
# 2차원 배열
# np.array() 안에는 하나의 자료구조만 들어가야 한다.
# np.array([1,2],[3,4]) -> 오류
b = np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


In [56]:
# b[행, 열]
b[1,1] # 4
b[1,0] # 3

3

In [60]:
# 실습하기
# b의 모든 행의 1열을 출력하라
b[:, 1]

array([2, 4])

# Pandas

### Series
- R의 vector와 같은 pandas의 2가지 데이터 구조 중 하나

In [64]:
# R의 벡터형과 같은 형식으로 만들어 줄 때
# pandas의 Series를 사용하며, 이때, 매개변수로 리스트 자료구조를 넣어준다.
s = pd.Series([1,2,3,4])

In [65]:
s[0]
s[1]
s[:]

0    1
1    2
2    3
3    4
dtype: int64

In [68]:
# 인덱스 이름을 가진 시리즈 만들기
s = pd.Series([99000,50000,30000], index=['서울','부산','인천'])
s

서울    99000
부산    50000
인천    30000
dtype: int64

In [71]:
# 실습하기
# s 시리즈에서 부산의 값을 출력하기
print(s[1])
print(s['부산'])

50000


## DataFrame
- R의 data.frame과 동일한 pandas의 2가지 자료구조 중 하나

In [74]:
dict1 = {'서울':[1,2,3,4], '부산':[100,200,300,400]}
df = pd.DataFrame(dict1)

In [78]:
# 파이썬에서 데이터프레임을 출력할 때
# display() 메소드를 자동으로 생성해준다.
# 데이터프레임을 두번 출력하고 싶다면
# print가 아니라 display()를 두번 사용하면 된다.
display(df)
display(df)

서울   부산
0   1  100
1   2  200
2   3  300
3   4  400

서울   부산
0   1  100
1   2  200
2   3  300
3   4  400

In [79]:
df['서울']

0    1
1    2
2    3
3    4
Name: 서울, dtype: int64

In [81]:
# R에서 $로 컬럼을 찾는 것과 같은 방식
# 컬럼명은 한글이 아니라 영어로 하는 것이 오류를 줄이는데 도움이 된다.
df.서울

0    1
1    2
2    3
3    4
Name: 서울, dtype: int64

In [83]:
# 데이터프레임 관련 메소드
display(df)
df.index

서울   부산
0   1  100
1   2  200
2   3  300
3   4  400

RangeIndex(start=0, stop=4, step=1)

In [84]:
len(df.index)

4

In [85]:
df.columns

Index(['서울', '부산'], dtype='object')

In [86]:
list(df.columns) # list 형으로 형 변환

['서울', '부산']